version: "3.9"

services:
        
        ccd_simulator:
                image: juanmimm/ubuntu-indigo
                ports:
                  - 8000:8000
                command: indigo_server -p 8000 indigo_ccd_simulator
        
        gps_simulator:
                image: juanmimm/ubuntu-indigo
                ports:
                  - 8001:8001
                command: indigo_server -p 8001 indigo_gps_simulator
        
        rotator_simulator:
                image: juanmimm/ubuntu-indigo
                ports:
                  - 8002:8002
                command: indigo_server -p 8002 indigo_rotator_simulator
